### PR TITLE
Make the simulator easier to use.

### PR DESCRIPTION
**Pull request by ericonr**
This PR is basically to make model development easier.
The changes were:
* Add Integration and Differentiation blocks, so that you are able to perform these operations without having to think of how to set up the ODE block (which is the basis of these blocks);
* Add the Time Variable, which holds the time of the simulation;
* Make changes to the `__init__` files, enabling easier imports, if one so wishes.

### CODE REVIEW

**Comment by masfaraud** [comment]
I'm not forgetting your PR, I'll review it when on vacations :)

**Comment by ericonr** [comment]
No problem! I might have more stuff to add when you decide to take a look at it :D

**Comment by masfaraud** [comment]
I merged your PR. What I changed:
simplified blocks and signals you defined are moved in files.
Your time class was changed to a simple instantiation of ramp with amplitude = 1  and can be found as bms.signals.functions.unit_ramp

**Comment by masfaraud** [comment]
Thanks for your time, I'll try to be more reactive in the future!

**Pull request merged**
