### PR TITLE
changing base classes to new style classes

### PR DESCRIPTION
**Pull request by pjadzinsky**

### CODE REVIEW

**Comment by ilayn** [comment]
In python 3 this is by default and Py2 is virtually done with.

**Comment by pjadzinsky** [comment]
I see..., but shouldn't then the project be limited to python 3 if that is the intention? I'm adding this module to a larger project that is in python 2 and unless necessary, don't see why it should be restricted to one version.

**Comment by ilayn** [comment]
It's more of an evolution of the Python. Version 2 would practically be dead very soon and I don't think default class in Python 2 compared to new style is a limitation by itself. Hence it would be a historical artifact not a restriction. 

I don't have a strong opinion about this though. It's up to the maintainer's preference.

**Comment by masfaraud** [comment]
I don't think we should support python2, it is supposed to be dead in 2020.

**Pull request closed without merging**
