### PR TITLE
Add better formatting, use mainly numpy functions for math, and add more comments to ODE block.

### PR DESCRIPTION
**Pull request by ericonr**
* By making the code compliant to PEP8, it is easier to read and make sense of;
* Using mainly `numpy` makes the code more uniform;
* It would be nice to explain the ODE function even more, because it seems powerful but it is hard to understand what it's doing.

### CODE REVIEW

**Comment by ericonr** [comment]
I'm thinking about making the `FunctionBlock` able to take more than one input, as well.

**Comment by masfaraud** [comment]
Hi, It seems that you forked from an old version, can you merge your branch from the current master and make a new pull request? As you changed a lot of things with the PEP8 syntax, merging will make the code regress.

**Comment by ericonr** [comment]
I couldn't find any new commits on your master branch... Your last commits are from Mar 1

**Comment by masfaraud** [comment]
Sorry, I didn't check well the code.
The pull request is now merged!

**Pull request merged**
